spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_app_dev
    username: recipe_app_dev_user
    password: password
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#Uncomment at Database initialization - Creates danvarga_database_create.sql
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: danvarga_database_create.sql